config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  devise_for :users, controllers: { registrations: 'users/registrations' }
  root to: "newsfeeds#show"
  resources :posts, only: %i[show create edit update destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_rich_text :content
  validates :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :omniauthable, :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable, :lockable, :trackable

  has_many :posts

  concerning :Presenter do
    def display_name
      email.split('@').first&.humanize
    end
  end

  concerning :Profile do
    included do
      enum gender: { female: 0, male: 1, other: 2 }

      before_create do
        set_unique_username
      end

      before_save do
        self.display_name = "#{self.first_name} #{self.last_name}"
      end

      private

      def set_unique_username
        username_candidate = "#{self.first_name}.#{self.last_name}".parameterize(separator: '')
        username_indexes = User.where("username ~ ?", "\\A#{username_candidate.split('').join('\\.?')}\\.?\\d*\\Z")
          .pluck(:username)
          .map { |username| username.delete(".") }
          .map { |username| username.scan(/\A#{username_candidate}(\d*)\z/) }
          .flatten
          .map(&:to_i)
          .sort
          .last(100_000)

        available_index = nil
        for i in 0...username_indexes.length do
          if username_indexes[i + 1].nil? || username_indexes[i] + 1 != username_indexes[i + 1]
            available_index = username_indexes[i] + 1
            break
          end
        end
        self.username = [self.first_name, self.last_name, available_index].compact.join('.').parameterize(separator: '.')
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/newsfeeds_controller.rb
class NewsfeedsController < ApplicationController
  before_action :authenticate_user!

  def show
    @new_post = Post.new
    @posts = current_user.
      posts.includes(:user).
      with_rich_text_content_and_embeds.
      order(created_at: :desc)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = current_user.posts.all
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # POST /posts or /posts.json
  def create
    @post = current_user.posts.build(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_back(fallback_location: root_url, notice: "Post was successfully created.") }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { redirect_back(fallback_location: root_url, status: :unprocessable_entity, alert: @post.errors.full_messages.to_sentence) }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to root_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = current_user.posts.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def post_params
    params.require(:post).permit(:content)
  end
end

app/controllers/timelines_controller.rb
class TimelinesController < ApplicationController
  before_action :authenticate_user!

  def show
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    build_resource(sign_up_params)

    resource.save
    yield resource if block_given?
    if resource.persisted?
      if resource.active_for_authentication?
        set_flash_message! :notice, :signed_up
        sign_up(resource_name, resource)
        respond_with resource, location: after_sign_up_path_for(resource)
      else
        set_flash_message! :notice, :"signed_up_but_#{resource.inactive_message}"
        expire_data_after_sign_in!
        respond_with resource, location: after_inactive_sign_up_path_for(resource)
      end
    else
      clean_up_passwords resource
      set_minimum_password_length
      respond_to do |format|
        format.turbo_stream do
          render turbo_stream: turbo_stream.replace(resource,
            partial: 'devise/registrations/form',
            locals: { resource: resource, resource_name: resource_name }
          )
        end
        format.html
      end
    end
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[username first_name last_name mobile_number birthdate gender])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/heroicon_helper.rb
# frozen_string_literal: true

module HeroiconHelper
  include Heroicon::Engine.helpers
end

app/helpers/newsfeeds_helper.rb
module NewsfeedsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/application/_alerts.html.erb
<% if notice %>
  <div class="relative py-3 pl-4 pr-10 leading-normal text-blue-700 bg-blue-100 rounded-lg mb-2" role="alert" data-controller="alert" data-transition-in="transition: 0.5s; transform:translate(0, 0)" data-transition-out="transition: 0.5s; transform:translate(100vw, 0)" data-delay-out="600" style="transform:translate(100vw, 0)">
    <p><%= notice %></p>
    <span class="absolute inset-y-0 right-0 flex items-center mr-4 cursor-pointer" data-action="alert#close">
      <%= heroicon "x", options: { class: "w-4 h-4 fill-current" } %>
    </span>
  </div>
<% end %>

<% if alert %>
  <div class="relative py-3 pl-4 pr-10 leading-normal text-red-700 bg-red-100 rounded-lg mb-2" role="alert" data-controller="alert" data-transition-in="transition: 0.5s; transform:translate(0, 0)" data-transition-out="transition: 0.5s; transform:translate(100vw, 0)" data-delay-out="600" style="transform:translate(100vw, 0)">
    <p><%= alert %></p>
    <span class="absolute inset-y-0 right-0 flex items-center mr-4 cursor-pointer transition ease-in-out duration-100" data-action="click->alert#close">
      <%= heroicon "x", options: { class: "w-4 h-4 fill-current" } %>
    </span>
  </div>
<% end %>

app/views/application/_left_bar.html.erb
<nav class="flex-none w-40 lg:w-52 text-sm p-1 pt-3 pr-0 hidden md:block">
  <div class="flex mb-1 p-1 border border-transparent rounded hover:bg-gray-50 hover:border-gray-200">
    <%= image_tag Identicon.data_url_for(current_user.display_name, 80, [255, 255, 255]), size: "20x20", class: "w-5 h-5 rounded-full mr-1.5" %>
    <div><%= current_user.display_name %></div>
  </div>
  <div class="flex p-1 border border-transparent rounded hover:bg-gray-50 hover:border-gray-200">
    <%= heroicon "newspaper", variant: :outline, options: { width: 20, height: 20, class: "mr-1.5" }, path_options: { stroke_width: 1.5 } %>
    News Feed
  </div>
  <h1 class="font-bold text-xs mt-3 mb-0.5 ml-1.5">Shortcuts</h1>
  <h1 class="font-bold text-xs mt-3 mb-0.5 ml-1.5">Explore</h1>
  <div class="flex p-1 border border-transparent rounded hover:bg-gray-50 hover:border-gray-200">
    <%= heroicon "calendar", variant: :outline, options: { width: 20, height: 20, class: "mr-1.5" }, path_options: { stroke_width: 1.5 } %>
    <div class="flex-grow">Events</div>
    <div class="self-center text-xs font-semibold text-gray-400 mr-0.5">0</div>
  </div>
  <div class="flex p-1 border border-transparent rounded hover:bg-gray-50 hover:border-gray-200">
    <%= heroicon "user-group", variant: :outline, options: { width: 20, height: 20, class: "mr-1.5" }, path_options: { stroke_width: 1.5 } %>
    <div class="flex-grow">Groups</div>
  </div>
  <div class="flex p-1 border border-transparent rounded hover:bg-gray-50 hover:border-gray-200">
    <%= heroicon "flag", variant: :outline, options: { width: 20, height: 20, class: "mr-1.5" }, path_options: { stroke_width: 1.5 } %>
    <div class="flex-grow">Pages</div>
  </div>
  <div class="flex p-1 border border-transparent rounded hover:bg-gray-50 hover:border-gray-200">
    <%= heroicon "users", variant: :outline, options: { width: 20, height: 20, class: "mr-1.5" }, path_options: { stroke_width: 1.5 } %>
    <div class="flex-grow">Friend Lists</div>
  </div>
  <div class="flex p-1 border border-transparent rounded hover:bg-gray-50 hover:border-gray-200">
    <%= heroicon "bookmark", variant: :outline, options: { width: 20, height: 20, class: "mr-1.5" }, path_options: { stroke_width: 1.5 } %>
    <div class="flex-grow">Saved</div>
  </div>
  <div class="flex p-1 border border-transparent rounded hover:bg-gray-50 hover:border-gray-200">
    <%= heroicon "clock", variant: :outline, options: { width: 20, height: 20, class: "mr-1.5" }, path_options: { stroke_width: 1.5 } %>
    <div class="flex-grow">Memories</div>
  </div>

  <div class="text-xs mt-8 ml-1.5">
    Privacy &middot;
    Terms &middot;
    Cookies &middot;
    More &middot;
    &copy; You
  </div>
</nav>

app/views/application/_navbar.html.erb
<nav class="bg-blue-800 text-white text-sm h-9 no-underlined-links">
  <div class="container mx-auto flex gap-x-2">
    <div class="font-bold py-2 whitespace-nowrap"><%=link_to "the Social Network", root_path %></div>
    <div class="flex-grow md:hidden"></div>
    <div class="flex-grow py-1.5 hidden md:block">
      <form>
        <div class="flex bg-white rounded-sm h-6 text-black px-1 lg:w-72">
          <input type="text" placeholder="Search" class="flex-grow outline-none" />
          <%= heroicon "search", variant: :outline, options: { width: 16, height: 16, class: "self-center text-gray-600" }, path_options: { stroke_width: 2.5 } %>
        </div>
      </form>
    </div>
    <div class="flex flex-nowrap">
      <%= image_tag Identicon.data_url_for(current_user.display_name, 80, [255, 255, 255]), class: "h-6 w-6 rounded-full block mt-1.5 mr-1.5" %>
      <div class="font-medium py-2 whitespace-nowrap"><%= current_user.display_name %></div>
    </div>
    <div class="text-xl font-extralight text-blue-900 py-0.5">|</div>
    <div class="font-medium py-2">Home</div>
    <div class="text-xl font-extralight text-blue-900 py-0.5">|</div>
    <div class="font-medium py-2 whitespace-nowrap">Find friends</div>
    <div class="text-xl font-extralight text-blue-900 py-0.5">|</div>
    <div class="py-2"><%= heroicon "users", options: { width: 20, height: 20 } %></div>
    <div class="py-2"><%= heroicon "chat-alt-2", options: { width: 20, height: 20 } %></div>
    <div class="py-2"><%= heroicon "bell", options: { width: 20, height: 20 } %></div>
    <div class="text-xl font-extralight text-blue-900 py-0.5">|</div>
    <div class="py-2"><%= heroicon "question-mark-circle", options: { width: 20, height: 20 } %></div>
    <div class="relative py-2" data-controller="dropdown">
      <div data-action="click->dropdown#toggle click@window->dropdown#hide" role="button" data-dropdown-target="button" tabindex="0" class="outline-none">
        <%= heroicon "chevron-down", options: { width: 20, height: 20 } %>
      </div>
      <div data-dropdown-target="menu" class="absolute right-0 w-48 mt-2 hidden z-50">
        <div class="bg-white text-gray-600 shadow rounded border overflow-hidden">
          <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "block px-4 py-2 hover:bg-gray-100", role: "menuitem" %>
        </div>
      </div>
    </div>
  </div>
</nav>

app/views/application/_right_bar.html.erb
<aside class="flex-none w-56 lg:w-72 py-2 hidden sm:block">
  <section class="bg-white border border-gray-200 rounded p-2 pt-0">
    <div class="flex">
      <h1 class="flex-grow font-bold text-xs mt-3 mb-2">Online friends</h1>
      <div class="self-center relative py-2 mr-1" data-controller="dropdown">
        <div data-action="click->dropdown#toggle click@window->dropdown#hide" role="button" data-dropdown-target="button" tabindex="0" class="outline-none">
          <%= heroicon "search", variant: :outline, options: { width: 20, height: 20 }, path_options: { stroke_width: 1.5 } %>
        </div>
        <div data-dropdown-target="menu" class="absolute right-0 w-72 mt-2 hidden z-50">
          <div class="bg-white text-gray-600 shadow rounded border overflow-hidden text-sm">
            <div class="px-1 py-2">
              <input type="search" class="w-full" />
            </div>
          </div>
        </div>
      </div>

      <div class="self-center relative py-2 mr-1 ml-1" data-controller="dropdown">
        <div data-action="click->dropdown#toggle click@window->dropdown#hide" role="button" data-dropdown-target="button" tabindex="0" class="outline-none">
          <%= heroicon "dots-horizontal", variant: :outline, options: { width: 20, height: 20 }, path_options: { stroke_width: 1.5 } %>
        </div>
        <div data-dropdown-target="menu" class="absolute right-0 w-48 mt-2 hidden z-50">
          <div class="bg-white text-gray-600 shadow rounded border overflow-hidden text-sm">
            <div class="px-4 py-2 hover:bg-gray-100">
              Mute
            </div>
            <div class="px-4 py-2 hover:bg-gray-100">
              Appear Offline
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="online-users">
      <div class="flex hover:bg-gray-100 rounded p-2">
        <div class="self-center relative mr-2">
          <%= image_tag Identicon.data_url_for(current_user.display_name, 80, [255, 255, 255]), size: "30x30", class: "rounded-full w-7 h-7" %>
          <div class="absolute w-3 h-3 bg-green-500 rounded-full -bottom-0.5 -right-0.5 border-2 border-white"></div>
        </div>
        <div class="text-sm font-medium self-center"><%= current_user.display_name %></div>
      </div>
    </div>
  </section>
</aside>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>the Social Network</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= javascript_pack_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_pack_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body class="bg-gray-100">
    <%= render partial: "navbar" %>
    <section class="flex container gap-x-2 mx-auto text-gray-600">
      <%= render partial: "left_bar" %>
      <%= yield %>
      <%= render partial: "right_bar" %>
    </section>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>the Social Network</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= javascript_pack_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_pack_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body class="bg-blue-50">
    <nav class="flex bg-blue-800 h-20 px-4 text-white">
      <h1 class="flex-grow self-end text-4xl font-extrabold mx-2 my-2 no-underlined-links">
        <%= link_to "the Social Network", root_path %>
      </h1>

      <%= yield :navbar %>
    </nav>

    <section class="m-4">
      <%= render partial: "alerts" %>
    </section>
    <div class="devise">
      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <header class="text-xs font-semibold bg-gray-100 p-2 pb-1.5 border-b rounded-t">
    <%= post.new_record? ? "Create Post" : "Edit Post" %>
  </header>
  <section class="flex p-2 pb-1 mb-1">
    <%= image_tag Identicon.data_url_for(current_user.display_name, 80, [255, 255, 255]), size: "40x40", class: "w-10 h-10 rounded-full mr-2" %>
    <div class="flex-grow text-sm" style="width: calc(100% - 60px)">
      <%= form.rich_text_area :content, placeholder: "What's on your mind?" %>
    </div>
  </section>
  <hr class="mx-auto w-11/12">
  <section class="flex gap-x-2 px-3 py-2">
    <div class="flex bg-gray-100 hover:bg-gray-200 rounded-full px-2 py-1 text-xs font-semibold">
      <%= heroicon "tag", variant: :outline, options: { width: 20, height: 20, class: "mr-1" }, path_options: { stroke_width: 1.5 } %>
      <div class="self-center">Tag friends</div>
    </div>
    <div class="flex bg-gray-100 hover:bg-gray-200 rounded-full px-2 py-1 text-xs font-semibold">
      <%= heroicon "location-marker", variant: :outline, options: { width: 20, height: 20, class: "mr-1" }, path_options: { stroke_width: 1.5 } %>
      <div class="self-center">Check in</div>
    </div>
    <div class="flex bg-gray-100 hover:bg-gray-200 rounded-full px-2 py-1 text-xs font-semibold">
      <%= heroicon "emoji-happy", variant: :outline, options: { width: 20, height: 20, class: "mr-1" }, path_options: { stroke_width: 1.5 } %>
      <div class="self-center">Feeling</div>
    </div>
  </section>
  <footer class="p-2 border-t bg-gray-50 rounded-b">
    <%= form.submit post.new_record? ? "Post" : "Update Post", class: "bg-blue-700 text-white w-full border border-blue-900 text-sm font-medium p-1 rounded-sm active:bg-blue-900" %>
  </footer>
<% end %>

app/views/posts/_post.html.erb
<article class="bg-white border border-gray-200 rounded mt-2">
  <header class="flex px-2 pt-2">
    <%= image_tag Identicon.data_url_for(post.user.display_name, 80, [255, 255, 255]), size: "40x40", class: "w-10 h-10 rounded-full mr-2" %>
    <div class="flex-grow">
      <div class="text-sm font-semibold"><%= post.user.display_name %></div>
      <div class="text-xs mt-0.5">
        <%= link_to time_ago_in_words(post.created_at), post_path(post) %>
        &middot;
        <%= heroicon "globe", options: { width: 14, height: 14, class: "mr-1 inline mb-0.5" }, path_options: { stroke_width: 1.5 } %>
      </div>
    </div>
    <div class="relative" data-controller="dropdown">
      <div data-action="click->dropdown#toggle click@window->dropdown#hide" role="button" data-dropdown-target="button" tabindex="0" class="outline-none" aria-label="More options">
        <%= heroicon "dots-horizontal", options: { width: 20, height: 20, class: "mr-1 inline mb-0.5" }, path_options: { stroke_width: 1.5 } %>
      </div>
      <div data-dropdown-target="menu" class="absolute right-0 mt-2 hidden w-72 z-50">
        <div class="bg-white text-gray-600 shadow rounded border overflow-hidden text-sm font-medium no-underlined-links">
          <div class="flex px-3 py-2 hover:bg-gray-100">
            <%= heroicon "bookmark", variant: :outline, options: { width: 20, height: 20, class: "w-5 mr-1.5" }, path_options: { stroke_width: 1.5 } %>
            Save
          </div>
          <%= link_to edit_post_path(post), class: "flex px-3 py-2 hover:bg-gray-100" do %>
            <%= heroicon "pencil", variant: :outline, options: { width: 20, height: 20, class: "w-5 mr-1.5" }, path_options: { stroke_width: 1.5 } %>
            Edit
          <% end if current_user && post.user == current_user %>
          <div class="flex px-3 py-2 hover:bg-gray-100">
            <%= heroicon "globe", variant: :outline, options: { width: 20, height: 20, class: "w-5 mr-1.5" }, path_options: { stroke_width: 1.5 } %>
            Edit audience
          </div>
          <div class="flex px-3 py-2 hover:bg-gray-100">
            <%= heroicon "bell", variant: :outline, options: { width: 20, height: 20, class: "w-6 mr-1.5 text-center" }, path_options: { stroke_width: 1.5 } %>
            Turn on/off Notifications for this Post
          </div>
          <%= link_to post_path(post), method: :delete, class: "flex px-3 py-2 hover:bg-gray-100", data: { confirm: "Are you sure?" } do %>
            <%= heroicon "trash", variant: :outline, options: { width: 20, height: 20, class: "w-5 mr-1.5" }, path_options: { stroke_width: 1.5 } %>
            Delete
          <% end if current_user && post.user == current_user %>
          <div class="flex px-3 py-2 hover:bg-gray-100">
            <%= heroicon "eye-off", variant: :outline, options: { width: 20, height: 20, class: "w-5 mr-1.5 text-center" }, path_options: { stroke_width: 1.5 } %>
            Hide Post
          </div>
          <div class="flex px-3 py-2 hover:bg-gray-100">
            <%= heroicon "eye-off", variant: :outline, options: { width: 20, height: 20, class: "w-5 mr-1.5" }, path_options: { stroke_width: 1.5 } %>
            Hide all from ...
          </div>
          <div class="flex px-3 py-2 hover:bg-gray-100">
            <%= heroicon "shield-exclamation", variant: :outline, options: { width: 20, height: 20, class: "w-5 mr-1.5" }, path_options: { stroke_width: 1.5 } %>
            Report post to group admin/admin
          </div>
        </div>
      </div>
    </div>
  </header>

  <main>
    <div class="text-sm mx-2 my-2"><%= post.content %></div>
    <%= image_tag "https://via.placeholder.com/650x350", class: "w-full" %>
    <div class="bg-gray-100 px-4 py-2 border-b border-gray-200">
      <div class="text-gray-500 font-light uppercase text-xs">Source</div>
      <div class="font-medium text-gray-900">Title</div>
      <div class="text-gray-500 font-light text-sm">Subtitle</div>
    </div>
    <div class="flex px-4 py-2 text-sm">
      <div class="flex-grow">👍 Tom and 2 others</div>
      <div>10 comments</div>
    </div>
  </main>
  <hr class="mx-auto w-11/12">
  <footer class="flex py-2 border-b">
    <div class="flex-1 relative text-center" data-controller="dropdown">
      <div data-action="click->dropdown#toggle click@window->dropdown#hide" role="button" data-dropdown-target="button" tabindex="0" class="flex justify-center outline-none text-sm font-medium">
        <%= heroicon "thumb-up", variant: :outline, options: { width: 20, height: 20, class: "mr-1 inline mb-0.5" }, path_options: { stroke_width: 1.5 } %>
        <div>Like</div>
      </div>
      <div data-dropdown-target="menu" class="absolute -left-1/4 mt-2 hidden z-50">
        <div class="bg-white shadow rounded-xl border overflow-hidden p-2 w-72">
          👍
          🥰
          🎉
          🫂
          🤣
          😮
          🤔
          😑
          😢
          😤
        </div>
      </div>
    </div>
    <div class="flex-1 text-center">
      <div class="flex justify-center outline-none text-sm font-medium">
        <%= heroicon "chat-alt", variant: :outline, options: { width: 20, height: 20, class: "mr-1 inline mb-0.5" }, path_options: { stroke_width: 1.5 } %>
        Comment
      </div>
    </div>
    <div class="flex-1 text-center">
      <div class="flex justify-center outline-none text-sm font-medium">
        <%= heroicon "share", variant: :outline, options: { width: 20, height: 20, class: "mr-1 inline mb-0.5" }, path_options: { stroke_width: 1.5 } %>
        Share
      </div>
    </div>
  </footer>
  <aside class="comments pt-3">
    <div class="flex px-2 pb-1">
      <%= image_tag Identicon.data_url_for(post.user.display_name, 80, [255, 255, 255]), class: "h-8 w-8 rounded-full block mt-1.5 mr-1.5" %>
      <div>
        <div class="bg-gray-100 rounded-full px-3 py-1 text-sm mb-0.5">
          <span class="font-medium text-blue-700">Name</span>
          Comment
          <%# ...
            Hide
            Report %>
        </div>
        <div class="text-xs ml-3">
          Like
          &middot;
          Comment
          &middot;
          1 min
        </div>
      </div>
    </div>
    <div class="flex pl-12 p-2">
      <%= image_tag Identicon.data_url_for(post.user.display_name, 80, [255, 255, 255]), class: "h-5 w-5 rounded-full block mt-1.5 mr-1.5" %>
      <div>
        <div class="bg-gray-100 rounded-full px-3 py-1 text-sm mb-0.5">
          <span class="font-medium text-blue-700">Name</span>
          Comment
          <%# ...
            Hide
            Report %>
        </div>
        <div class="text-xs ml-3">
          Like
          &middot;
          Comment
          &middot;
          1 min
        </div>
      </div>
    </div>
  </aside>
  <form class="flex p-2 pt-1">
    <%= image_tag Identicon.data_url_for(post.user.display_name, 80, [255, 255, 255]), class: "h-8 w-8 rounded-full block mt-1.5 mr-1.5" %>
    <div class="flex-grow flex border bg-gray-100 border-gray-300 rounded-lg px-2 width-full">
      <div class="grow-wrap flex-grow text-sm">
        <textarea rows="1" class="outline-none bg-transparent" placeholder="Write a comment..." onInput="this.parentNode.dataset.replicatedValue = this.value"></textarea>
      </div>

      <%= heroicon "photograph", variant: :outline, options: { width: 20, height: 20, class: "self-end mr-1 mb-2" }, path_options: { stroke_width: 1.5 } %>
    </div>
  </form>
</article>

app/views/posts/edit.html.erb
<main class="flex-grow pt-2 pb-2 ml-2 mr-2 md:ml-0 sm:mr-0">
  <%= render partial: "alerts" %>
  <section class="bg-white border border-gray-200 rounded mb-2">
    <%= render partial: "posts/form", locals: { post: @post } %>
  </section>
</main>

app/views/posts/show.html.erb
<main class="flex-grow pt-2 pb-2 ml-2 mr-2 md:ml-0 sm:mr-0">
  <%= render partial: "alerts" %>
  <div class="posts">
    <%= render partial: "posts/post", locals: { post: @post } %>
  </div>
</main>